# -*- coding: utf-8 -*-
"""EDA on Telecom Churn by Mansi Gupta.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D67V89xV2aAROP8Tm7lNZSZz9moi9FMq

# **Project Name**    - **TELECOM CHURN ANALYSIS**

##### **Project Type**    - EDA
##### **Contribution**    - Individual
##### **Team Member** -Mansi Gupta

# **Project Summary** -

In this exploratory data analysis (EDA) project, we investigated telecom churn data to understand customer behavior and factors influencing churn. The project involved several key steps:

Data Wrangling: We began by preprocessing the dataset, handling missing values, converting categorical variables into numerical format, and creating new columns as needed. This ensured the data was clean and suitable for analysis.

Univariate Analysis: We conducted univariate analysis to explore individual variables such as customer demographics, service plans, call usage, and customer service interactions. This helped us understand the distribution and characteristics of each variable.

Bivariate Analysis: Next, we analyzed the relationship between pairs of variables to identify potential correlations or associations. For example, we examined the impact of service plans (e.g., International Plan, Voice Mail Plan) on churn rates and explored how call usage patterns vary among churned and non-churned customers.

Multivariate Analysis: We extended our analysis to consider multiple variables simultaneously. This involved techniques such as correlation analysis, heatmaps, and pair plots to uncover complex relationships and interactions among variables. We also explored regional variations in churn rates and revenue generation across different area codes.

Insights and Recommendations: Throughout the analysis, we gained valuable insights into customer behavior, churn drivers, and areas of improvement for the telecom company. These insights informed actionable recommendations aimed at reducing churn, improving customer retention, and optimizing revenue generation strategies.

Overall, this EDA project provided a comprehensive understanding of telecom churn dynamics, empowering the company to make data-driven decisions and implement targeted interventions to enhance customer satisfaction and business performance

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

Orange Telecom, a leading multinational telecommunications corporation, faces the challenge of customer churn, which significantly impacts its business sustainability and revenue. The objective of this analysis is to explore the Orange Telecom Churn Dataset, identifying key factors contributing to customer churn. The goal is to uncover actionable insights that enable Orange Telecom to implement targeted retention strategies and enhance customer satisfaction. Through this analysis, we aim to provide recommendations that empower Orange Telecom to proactively address churn and improve overall customer retention rates

#### **Define Your Business Objective?**

The primary objective is to reduce customer churn and enhance customer retention for the telecommunications company.

State: Analyze churn rates and customer behavior patterns across different states to identify regional trends and preferences.

Account Length: Investigate whether longer account lengths correlate with lower churn rates, indicating higher customer loyalty.

International Plan: Determine the impact of having an international calling plan on churn rates and revenue generation.

Voice Mail Plan: Explore the relationship between having a voicemail plan and customer churn, as well as its influence on overall service usage.

Service Usage Metrics: Examine total minutes, calls, and charges across different time periods (day, evening, night) to understand usage patterns and revenue contributions.

Customer Service Calls: Assess the effect of customer service interactions on churn rates and identify potential areas for improvement in service quality.

Number of Voicemail Messages: Investigate whether voicemail usage influences customer retention and engagement.

Area Code: Explore churn rates and revenue patterns across different area codes to identify geographical variations in customer behavior.

Revenue Metrics: Analyze revenue generated from different service components (daytime, evening, night, international) to prioritize revenue streams and optimize pricing strategies.

Total Intl Minutes/Calls/Charge: Understand the contribution of international calling to overall revenue and its impact on customer satisfaction and retention.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick

#filtering out the warning
import warnings
warnings.filterwarnings("ignore")

"""### Dataset Loading"""

# Load Dataset
from google.colab import drive
drive.mount("/content/drive")
telecom_df= pd.read_csv("/content/drive/My Drive/Telecom Churn.csv")

"""### Dataset First View"""

# Dataset First Look
telecom_df

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
print("Number of Rows are :", telecom_df.shape[0])
print("Number of Columns are :", telecom_df.shape[1])

"""### Dataset Information"""

# Dataset Info
telecom_df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
print("Count of duplicate values:", telecom_df.duplicated().sum())

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
telecom_df.isnull().sum()

# Visualizing the missing values
sns.heatmap(telecom_df.isnull(), cmap = "Blues")

"""### What did you know about your dataset?

This dataset contains telecommunications data for 3333 customers, with 20 columns representing various attributes. It has no duplicate or missing values. Key features include customer demographics like State and Area code, service plans such as International and Voice Mail, call details like duration and charges for daytime, evening, and nighttime calls, as well as international calls.

Additionally, it records the number of voicemail messages and customer service calls. The 'Churn' column indicates whether a customer has left the company (True) or not (False). Overall, the dataset provides insights into customer behavior, service usage patterns, and potential predictors of churn.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
telecom_df.columns

# Dataset Describe
telecom_df.describe()

"""### Variables Description

* State: The state where the customer is located.
* Account Length: The duration of time the customer has been with the company (in days).
* Area Code: The area code associated with the customer's phone number. 415 relates to San Francisco, 408 is of San Jose, and 510 is of Oakland.
* International Plan: Whether the customer has an international calling plan (yes/no).
* Voice Mail Plan: Whether the customer has a voicemail plan (yes/no).
* Number Vmail Messages: The number of voicemail messages the customer has.
* Total Day Minutes: The total number of minutes the customer used during the daytime.
* Total Day Calls: The total number of calls the customer made during the daytime.
* Total Day Charge: The total charge for daytime usage.
* Total Eve Minutes: The total number of minutes the customer used during the evening.
* Total Eve Calls: The total number of calls the customer made during the evening.
* Total Eve Charge: The total charge for evening usage.
* Total Night Minutes: The total number of minutes the customer used during the night.
* Total Night Calls: The total number of calls the customer made during the night.
* Total Night Charge: The total charge for nighttime usage.
* Total Intl Minutes: The total number of international minutes used by the customer.
* Total Intl Calls: The total number of international calls made by the customer.
* Total Intl Charge: The total charge for international usage.
* Customer Service Calls: The number of customer service calls made by the customer.
* Churn: This our Target Variable. Churn means whether the customer has churned (left) the company (True/False).

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
for i in telecom_df.columns:
  print("Number of unique values in", i ,"is :", telecom_df[i].nunique())

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
tele_df = telecom_df.copy()

#Adding new columns

# Columns that signifies customer number
tele_df.insert(0, 'Customer_number', tele_df.index + 1)

# Columns for the cost per minute for different time periods (day, evening, night, and international)
tele_df = tele_df.assign(day_charges_per_min=(tele_df['Total day charge']/ tele_df['Total day minutes']),
               eve_charges_per_min=(tele_df['Total eve charge'] / tele_df['Total eve minutes']),
               night_charges_per_min=(tele_df['Total night charge'] / tele_df['Total night minutes']),
               int_charges_per_min=(tele_df['Total intl charge'] / tele_df['Total intl minutes']))

# Columns for the revenue generated during different time periods (day, evening, night, and international)
tele_df = tele_df.assign(Revenue_day=(tele_df['Total day minutes'] * tele_df['Total day charge']).round(2),
               Revenue_eve=(tele_df['Total eve minutes'] * tele_df['Total eve charge']).round(2),
               Revenue_night=(tele_df['Total night minutes'] * tele_df['Total night charge']).round(2),
               Revenue_intl=(tele_df['Total intl minutes'] * tele_df['Total intl charge']).round(2))

print("Shape of the dataset after adding new columns is -")
tele_df.shape

pd.Series({columns : tele_df[columns].unique() for columns in tele_df})

tele_df.isnull().sum()

sns.heatmap(tele_df.isnull(), cmap = "coolwarm")

tele_df["int_charges_per_min"].fillna(tele_df["int_charges_per_min"].mean(), inplace=True)
tele_df["day_charges_per_min"].fillna(tele_df["day_charges_per_min"].mean(), inplace=True)
tele_df["eve_charges_per_min"].fillna(tele_df["eve_charges_per_min"].mean(), inplace=True)

tele_df.isnull().sum()

# Calculate total revenue earned
total_revenue = tele_df[['Revenue_day', 'Revenue_eve', 'Revenue_night', 'Revenue_intl']].sum().sum()

print("Total Revenue Earned:", total_revenue)

"""### What all manipulations have you done and insights you found?

**MANIPULAIONS**

Data Preparation: Created a duplicate of the dataset for manipulation and visualization purposes, ensuring the integrity of the original data.
Conducted a thorough check for null and missing values in the dataset, confirming its initial cleanliness and completeness.

Feature Engineering: Introduced new columns to enrich the dataset and facilitate deeper analysis:
Calculated charges per minute for different time dimensions (daytime, evening, and nighttime).
Derived columns to quantify revenue from various time dimensions and international plans, enhancing insights into revenue generation trends.

Null Value Handling: Identified 18 null values in the international charges per minute column and addressed them by imputing the mean value, ensuring data completeness and consistency.
Similarly, null values in the day and evening charge columns were filled with mean values, mitigating data inconsistencies and enabling accurate analysis.

**INSIGHTS**

After manipulation the I found that , it includes geographic location (State), tenure (Account Length), and service features like International and Voice Mail plans. Call metrics such as duration (Minutes), frequency (Calls), and associated charges provide insights into usage patterns. Additionally, variables like Customer Service Calls indicate interaction levels. The presence or absence of International and Voice Mail plans, along with call-related details, can influence customer churn (Churn). Understanding these variables enables deeper analysis of customer behavior, satisfaction, and potential predictors of churn, facilitating targeted strategies for customer retention and service enhancement.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1 - Churn Rate Among Customers
"""

# Chart - 1 visualization code
# Finding the count of churned and not churned customers
print("Total Customers are : 3333 ")
print(f'Number of customers not churned : {tele_df["Churn"].value_counts()[0]}')
print(f'Number of customers churned  : {tele_df["Churn"].value_counts()[1]}')


colors = ['#1f77b4', '#d62728']
explode = (0, 0.1)  # Explode the 'Churned' slice to highlight it

# Create a donut chart
fig, ax = plt.subplots()
ax.pie(tele_df["Churn"].value_counts(), explode=explode, labels=['Not Churned', 'Churned'], colors=colors, autopct='%1.2f%%', startangle=90, shadow = True)

# Draw a circle at the center with radius 0.60 to make it a donut chart
centre_circle = plt.Circle((0,0),0.50,fc='white')
fig.gca().add_artist(centre_circle)

# Equal aspect ratio ensures that pie is drawn as a circle
ax.axis('equal')

# Add a title
plt.title('Churn Rate Among Customers')

# Show the plot
plt.show()

"""##### 1. Why did you pick the specific chart?

Donut charts are used for visualizing data that shows the relationship between a whole and its parts, similar to pie charts. This can be useful when analyzing data distributions or comparing the sizes of different categories within a dataset.

##### 2. What is/are the insight(s) found from the chart?

Out of 3333 total customers, 2850 remain loyal, while 483 have churned. This suggests a churn rate of approximately 14.49%, which further suggests that there might be issues or factors causing customers to leave the service, emphasizing the importance of effective retention strategies to maintain customer satisfaction and business growth. Understanding and addressing the reasons behind customer churn is critical for improving overall customer retention and long-term business success.
With a retention rate of 85.51%, it's evident that a significant portion of customers are staying with the service. This could be attributed to effective customer retention strategies, such as loyalty programs, personalized offers, excellent customer service, or product improvements. Identifying and reinforcing these strategies could help maintain high retention rates.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here - Understanding churn and retention rates is crucial for the long-term success of a business. High churn rates can lead to loss of revenue, reduced market share, and increased customer acquisition costs. On the other hand, high retention rates can lead to higher customer lifetime value, increased brand loyalty, and sustainable business growth. Therefore, businesses should continuously monitor and optimize their churn and retention strategies to maximize customer satisfaction and profitability

#### Chart - 2- Churned customers' adoption of the  Voice mail plan
"""

# Chart - 2 visualization code
# Filter the DataFrame to select only churned customers
customer_churned = tele_df[tele_df["Churn"]== True]
print(customer_churned.groupby("Voice mail plan")[["Voice mail plan"]].value_counts())
# Create a new figure with specified size
plt.figure(figsize=(5,5))

# Plot a pie chart to visualize churn rate according to Voice mail plan
customer_churned["Voice mail plan"].value_counts().plot(kind="pie", labels=["No", "Yes"], autopct="%1.2f%%",
                                                       shadow=True, startangle=90, textprops={"fontsize":12},
                                                       explode=(0, 0.1))

# Set the title of the plot
plt.title("Churned customers' adoption of the Voice mail plan", fontsize=15)

# Show the plot
plt.show()

"""##### 1. Why did you pick the specific chart?

I chose a pie chart to visualize the adoption rate because it provides a clear representation of the proportion of churned customers with and without a Voice mail plan.

##### 2. What is/are the insight(s) found from the chart?

The insight is that a majority of customers, 403 out of the total, do not subscribe to the Voice mail plan, while only 80 customers have opted for it.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insights gained from the analysis of Voice mail plan adoption suggest opportunities for positive business impact by informing targeted marketing strategies and service enhancements to increase plan adoption. However, the low adoption rate indicates a potential missed revenue opportunity, posing a risk of negative growth if not addressed effectively through proactive measures to promote the plan and improve customer satisfaction.

#### Chart - 3 - churned customers' adoption of the International plan
"""

# Chart - 3 visualization code
# Filter the DataFrame to select only churned customers
customer_churned = tele_df[tele_df["Churn"]== True]
print(customer_churned.groupby("International plan")[["International plan"]].value_counts())
# Create a new figure with specified size
plt.figure(figsize=(5,5))
# Plot a pie chart to visualize churn rate according to Voice mail plan
customer_churned["International plan"].value_counts().plot(kind  = "pie", autopct = "%1.2f%%", shadow = True, textprops= {"fontsize":12}, explode = (0,0.1), startangle = 90 )
# Set the title of the plot
plt.title("Churned customers' adoption of the International plan",fontsize = 15)
# Show the plot
plt.show()

"""##### 1. Why did you pick the specific chart?

I chose a pie chart to visualize the adoption rate because it provides a clear representation of the proportion of churned customers with and without a International plan.

##### 2. What is/are the insight(s) found from the chart?

The insight is that among churned customers,a majority (346 out of the total), do not subscribe to the International plan, while only 137 customers have opted for it. Also churn rates are higher among customers without the International plan.
There may be an opportunity to increase revenue by promoting and encouraging more customers to subscribe to the International plan. This plan likely offers additional features or services for international calling, which, if marketed effectively, could attract more customers and boost revenue.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insights gained from analyzing churned customers' adoption of the International plan offer potential for positive business impact by informing targeted retention strategies and customer experience enhancements. However, the low adoption of the International plan among churned customers suggests missed revenue opportunities, posing a risk of negative growth if not addressed promptly

#### Chart - 4 - Distribution of Account Length by Churn Status
"""

# Set the style of seaborn
sns.set(style="whitegrid")

# Create a boxplot to show the distribution of account length based on churn status
plt.figure(figsize=(8, 6))
sns.boxplot(x='Churn', y='Account length', data=tele_df, palette='Set2')

# Add labels and title
plt.xlabel('Churn Status')
plt.ylabel('Account Length')
plt.title('Distribution of Account Length by Churn Status')

# Show the plot
plt.show()

"""##### 1. Why did you pick the specific chart?

I choose this plot because it shows central tendency, outliers

##### 2. What is/are the insight(s) found from the chart?

The median account lengths for both churned and non-churned customers fall within the range of 75 to 125 days, indicating a similarity in the central tendency of the two groups. Additionally, the interquartile ranges (IQR) for both groups are quite similar, suggesting comparable variability in account lengths. However, the boxplot for non-churned customers exhibits more outliers compared to the churned customers' boxplot, implying that non-churned customers have a wider range of account lengths , potentially indicating a more diverse customer base or longer-term engagements.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Understanding the similar median account lengths and comparable variability between churned and non-churned customers can inform customer retention strategies. Some non-churned customers have long-standing and potentially successful relationships with the company.

#### Chart - 5 - Relationships Between Call Usage and Churn Rate.
"""

# Chart - 5 visualization code
# Create a scatter plot or regression plot of total daytime minutes vs. churn rates

plt.figure(figsize=(15, 5))
plt.subplot(1,3,1)
sns.regplot(x='Total day minutes', y='Churn', data=tele_df , logistic=True, ci=None, scatter_kws={'alpha':0.2})

# Add labels and title
plt.xlabel('Total Daytime Minutes')
plt.ylabel('Churn (1 for True, 0 for False)')
plt.title('Relationship Between Total Daytime Minutes\n and Churn Rates')

plt.subplot(1,3,2)
sns.regplot(x='Total eve minutes', y='Churn', data=tele_df, logistic=True, ci=None, scatter_kws={'alpha':0.2})

# Add labels and title
plt.xlabel('Total eve Minutes')
plt.ylabel('Churn (1 for True, 0 for False)')
plt.title('Relationship Between Total eve Minutes\n and Churn Rates')

plt.subplot(1,3,3)
sns.regplot(x='Total night minutes', y='Churn', data=tele_df, logistic=True, ci=None, scatter_kws={'alpha':0.2})

# Add labels and title
plt.xlabel('Total night Minutes')
plt.ylabel('Churn (1 for True, 0 for False)')
plt.title('Relationship Between Total night Minutes\n and Churn Rates')



# Show plot
plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

This chart enables a comprehensive analysis of relationships between variables within a single visualization, facilitating insights into potential correlations or trends across the dataset

##### 2. What is/are the insight(s) found from the chart?

Total DayTime Minutes : The chart is showing a positive relationship with churn rate. This insight could indicate that customers who spend more time on daytime calls are more likely to churn.

Total eve Minutes : The chart is showing a moderate relationship with churn rate. This could imply that while there is still a tendency for churn rate to increase with higher evening call usage, the effect may be less pronounced or influenced by other factors.

Total night minutes : The chart is showing approximately constant or weak relationship with churn rate. This insight could indicate that factors other than night call usage play a more significant role in determining customer churn.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insights regarding the weak relationship between total night minutes and churn rate may not directly contribute to a positive business impact, as they suggest that night call usage alone may not significantly influence churn likelihood. However, this understanding can help avoid misallocation of resources towards ineffective retention efforts solely focused on evening call usage. Nonetheless, neglecting other factors contributing to churn, such as service quality or pricing, could lead to negative growth

#### Chart - 6 - Distribution of churn Customers
"""

# Filter the dataset for churned customers
churned_customers = tele_df[tele_df['Churn'] == True]

# Count the occurrences of each combination of International plan and Voice mail plan
plan_counts = churned_customers.groupby(['International plan', 'Voice mail plan']).size()
print(plan_counts)
# Define labels based on combinations of plans
labels = ['Neither', 'International plan', 'Voice mail plan', 'Both']

# Plotting the donut chart
plt.figure(figsize=(7,5))
plt.pie(plan_counts, labels=labels, autopct='%1.1f%%', startangle=90, colors=["#18C110","#3D589C","#FA580D","#DA4158"], wedgeprops=dict(width=0.4), explode = (0,0.1,0.1,0.1), shadow = True)
plt.title('Churned Customers with International and Voice Mail Plans')
plt.legend(labels, loc='upper right')
plt.gca().add_artist(plt.Circle((0,0),0.3,color='white'))
plt.axis('equal')
plt.show()

"""##### 1. Why did you pick the specific chart?

A donut pie chart showing the percentage of churned customers in different segments based on the International plan and Voice mail plan

##### 2. What is/are the insight(s) found from the chart?

Customers without an International plan have a higher churn rate compared to those with an International plan. This suggests that offering an International plan might contribute to retaining customers and reducing churn.

Customers without a Voice mail plan have a higher churn rate compared to those with a Voice mail plan. Providing a Voice mail plan might enhance customer engagement and satisfaction, leading to lower churn rates.

Customers with both an International plan and a Voice mail plan exhibit the lowest churn rate among the analyzed groups. This indicates that offering bundled services or incentives can effectively reduce churn and improve customer loyalty.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

A particular segment, such as customers without an International plan, has a higher churn rate, the company can focus on improving the value proposition or offering incentives to retain these customers. Conversely, insights revealing low churn rates in certain segments could highlight areas of strength that can be leveraged to retain customers across other segments.

#### Chart - 7- The churn distribution across states
"""

# Chart - 6 visualization code
# Grouping and unstacking the data
churn_by_state = tele_df.groupby("State")["Churn"].value_counts().unstack()

# Plotting the bar chart
ax = churn_by_state.plot(kind="bar", figsize=(20, 6), cmap='coolwarm')

# Adding labels and title
plt.xlabel("State", fontsize=14)  # x-axis label
plt.ylabel("Number of Customers", fontsize=14)  # y-axis label
plt.title("Churn Distribution by State", fontsize=16)  # Plot title

# Adding legend
plt.legend(title="Churn", fontsize=12)

# Rotating x-axis labels for better readability
plt.xticks(rotation=45, ha='right')

# Show plot
plt.show()

"""##### 1. Why did you pick the specific chart?

I choose bar plot to visualize churn distribution by state as it offers a clear comparison between the number of churned and non-churned customers across different states. Its simplicity allows for easy interpretation of the data, with each bar representing a state and its height indicating the respective customer counts.

##### 2. What is/are the insight(s) found from the chart?

It offers a comprehensive overview of churn distribution across various states, providing a bird's eye view of the overall customer retention landscape. By visually presenting the number of churned and non-churned customers per state, it gives valuable insights into geographic patterns of customer attrition. This information empowers stakeholders to identify regions with higher churn rates, guiding strategic decision-making in areas such as targeted retention efforts, resource allocation, and market expansion initiatives.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, the insights gained from analyzing the churn distribution among different states can indeed help create a positive business impact.
Regarding insights that may lead to negative growth, if the analysis reveals consistently high churn rates across multiple states or a significant increase in churn rates over time, it could indicate underlying issues within the business that need to be addressed.

#### Chart - 8  - Worst Performing State
"""

# Chart - 7 visualization code
worst_performing_state = tele_df.groupby("State")["Churn"].mean().sort_values(ascending = False).reset_index().head(10)
print(worst_performing_state)

# Plot the bar plot
plt.figure(figsize=(10,5))
ax = sns.barplot(data=worst_performing_state, x="State", y="Churn", palette= "coolwarm", width = 0.6)

# Adding labels and title
plt.xlabel("State", fontsize=12)
plt.ylabel("Churn Rate", fontsize=12)
plt.title("Worst_performing_state", fontsize=15)


# Add percentages on top of the bars
for p in ax.patches:
    ax.annotate(f'{p.get_height():.2f}%', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', fontsize=10, color='black', xytext=(0, 5),
                textcoords='offset points')

plt.show()

"""##### 1. Why did you pick the specific chart?

Bar plots are effective for comparing the churn rates of different states visually, allowing for easy identification of the top performing states.

##### 2. What is/are the insight(s) found from the chart?

States such as New Jersey (NJ), California (CA), and Texas (TX) exhibit notably high churn rates, indicating potential regional trends or challenges specific to these areas. High churn rates in densely populated states like California and Texas may reflect intense competition or dissatisfaction among customers, potentially driven by factors such as service quality, pricing, or competitor offerings.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Identifying the worst performing states allows businesses to focus on these areas for targeted interventions aimed at reducing churn. Understanding the unique characteristics and challenges of each state can help tailor retention strategies to address specific issues contributing to churn. Neglecting to address high churn rates in these states may lead to negative growth, resulting in revenue loss and reduced market competitiveness.

#### Chart - 9- Top Performing State
"""

# Chart - 8 visualization code
Top_performing_state= tele_df.groupby("State")["Churn"].mean().sort_values().reset_index().head(10)
print(Top_performing_state)

# Plotting the bar plot
plt.figure(figsize=(10,5))
ax = sns.barplot(data=Top_performing_state, x="State", y="Churn", palette="coolwarm", width = 0.6)

# Adding labels and title
plt.xlabel("State", fontsize=12)
plt.ylabel("Churn Rate", fontsize=12)
plt.title("Top_performing_state", fontsize=15)

for p in ax.patches:
    ax.annotate(f'{p.get_height():.2f}%', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', fontsize=10, color='black', xytext=(0, 5),
                textcoords='offset points')

plt.show()

"""##### 1. Why did you pick the specific chart?

Bar plots are effective for comparing churn rates across different states, allowing for easy identification of regions with low or high churn rates.

##### 2. What is/are the insight(s) found from the chart?

States such as Hawaii (HI), Alaska (AK), and Arizona (AZ) exhibit notably low churn rates, suggesting high levels of customer satisfaction and loyalty within these regions. This could be attributed to factors such as quality service, competitive pricing, and effective customer engagement strategies.
Analysis of states with low churn rates may reveal regional trends or characteristics that contribute to higher customer retention. Understanding these patterns can inform targeted marketing efforts and customer retention strategies tailored to the preferences and needs of customers in each state.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insights gained from analyzing states with low churn rates can positively impact the business by informing effective retention strategies and facilitating market expansion. However, neglecting to address high churn rates in underperforming regions may lead to negative growth, resulting in customer attrition and revenue loss.

#### Chart - 10 - Distribution of International Plan Across States
"""

# Chart - 9 visualization code
# Group the data by 'State' and 'International plan' and count the occurrences
grouped_data = tele_df.groupby(['State', 'International plan']).size().unstack(fill_value=0)
print(f"States with lowest no of International plan\n{grouped_data.sort_values(by = 'Yes').head()} ")
print(f"States with highest no of International plan\n {grouped_data.sort_values(by = 'Yes', ascending  = False).head()}")
# Plot the grouped bar chart
grouped_data.plot(kind='bar', stacked=True, cmap='coolwarm', figsize = (15,5))

# Set the title and labels
plt.title('Distribution of International Plan Across States')
plt.xlabel('State')
plt.ylabel('Count')

# Show the plot
plt.legend(title='International Plan')
plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

Comparing the heights of bars across states allows for the identification of regional disparities in international plan adoption. States with consistently higher or lower adoption rates may suggest underlying demographic, economic, or cultural factors influencing customer preferences.

##### 2. What is/are the insight(s) found from the chart?

The insight that we get are, the absence of international plan customers in Iowa (IA) and the lowest adoption rate in Louisiana (LA).
Possible reasons could be :
Illinois may have a larger population of frequent travelers or individuals with international connections
Louisiana's telecommunications market may be more competitive, offering a wider range of domestic calling plans that meet customers' needs without the need for international plans. In contrast, Iowa's market dynamics may not prioritize international calling features as heavily, resulting in fewer international plan offerings and lower adoption rates.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insights gained from analyzing international plan adoption across states can foster positive business impact by enabling targeted strategies and optimized resource allocation. However, market fragmentation and missed revenue opportunities resulting from regional variations in adoption rates could lead to negative growth if not addressed strategically.

#### Chart - 11 - Distribution of Voice mail plan Across States
"""

# Chart - 10 visualization code
# Group the data by 'State' and 'International plan' and count the occurrences
grouped_data = tele_df.groupby(['State', 'Voice mail plan']).size().unstack(fill_value=0)
print(f"States with lowest no of Voice mail plan\n {grouped_data.sort_values(by = 'Yes').head()} ")
print(f"States with highest no of Voice mail plan\n {grouped_data.sort_values(by = 'Yes', ascending  = False).head()}")
# Plot the grouped bar chart
grouped_data.plot(kind='bar', stacked=True, cmap='coolwarm', figsize = (15,5))
# Set the title and labels
plt.title('Distribution of Voice mail plan Across States')
plt.xlabel('State')
plt.ylabel('Count')

# Show the plot
plt.legend(title='Voice mail plan')
plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

Comparing the heights of bars across states allows for the identification of regional disparities in Voice mail plan adoption. States with consistently higher or lower adoption rates may suggest underlying demographic, economic, or cultural factors influencing customer preferences.

##### 2. What is/are the insight(s) found from the chart?

The comparison reveals significant variations in the adoption of voice mail plans across different states. States such as Washington (WA), California (CA), Pennsylvania (PA), Iowa (IA), and Louisiana (LA) exhibit lower numbers of voice mail plan subscribers compared to states like West Virginia (WV), Idaho (ID), Ohio (OH), Montana (MT), and Minnesota (MN) with higher subscriber counts.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

By understanding regional demand drivers and market dynamics, companies can optimize resource allocation, drive customer acquisition, and foster positive business growth. Neglecting to address regional disparities may hinder market expansion efforts and limit overall business growth potential.

#### Chart - 12 - Percentage of Customers with Voice mail plan and International plan
"""

# Chart - 11 visualization code

# Reshape the DataFrame using melt to create a tidy format
df2 = pd.melt(tele_df, id_vars=['Customer_number'], value_vars=['Voice mail plan','International plan'])

# Group the data by 'variable' and 'value', calculate counts, and unstack the DataFrame
df3 = df2.groupby(['variable','value']).count().unstack()

# Calculate the percentage of customers for each combination
df3 = df3 * 100 / len(tele_df)
print(df3)

# Define colors for the bar plot
colors = ['#1f77b4', '#d62728']

# Plot the stacked bar chart
ax = df3.loc[:,'Customer_number'].plot.bar(stacked=True, color=colors,
                                      figsize=(8,6), rot=0,
                                      width=0.2)

# Format y-axis labels as percentages
ax.yaxis.set_major_formatter(mtick.PercentFormatter())

# Set axis labels and title
ax.set_ylabel('% Customers', size=14)
ax.set_xlabel('')
ax.set_title('Percentage of Customers with Voice mail plan and International plan', size=14)

# Add legend and annotations to each bar
ax.legend(loc='center', prop={'size':14})

for p in ax.patches:
    width, height = p.get_width(), p.get_height()
    x, y = p.get_xy()
    ax.annotate('{:.0f}%'.format(height), (p.get_x() + .25 * width, p.get_y() + .4 * height),
                color='white',
                weight='bold',
                size=14)

"""##### 1. Why did you pick the specific chart?

Bar plots are effective for comparing quantitative data across different categories, allowing for easy comparison.

##### 2. What is/are the insight(s) found from the chart?

Approximately 9.69% of customers have opted for an international plan, In contrast, a higher proportion of customers (27.66%) have subscribed to voice mail plans, indicating a greater demand for this service.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Since large number of customer opted for voice mail plans, so the comapny must should privide offers to retain them. Also they should focuse on marketing startegies for international plan. Understanding customer preferences for these services enables targeted marketing efforts, enhancing customer retention and loyalty while driving revenue growth. However, disparities in adoption rates and underutilized services may contribute to churn if not addressed, leading to negative growth.

#### Chart - 13 - Churn by Area code
"""

# Chart - 12 visualization code
colors = ['#1f77b4', '#d62728']
area_churn = tele_df.groupby(['Area code','Churn']).size().unstack()
print(f"Churn as per area code is\n{area_churn}")
ax = (area_churn.T*100.0 / area_churn.T.sum()).T.plot(kind='bar',
                                                                width = 0.3,
                                                                stacked = True,
                                                                rot = 0,
                                                                figsize = (10,6),
                                                                color = colors)
ax.yaxis.set_major_formatter(mtick.PercentFormatter())
ax.legend(loc='best',prop={'size':14},title = 'Churn')
ax.set_ylabel('% Churn',size = 14)
ax.set_title('Churn by Area code',size = 14)

# Code to add the data labels on the stacked bar chart
for p in ax.patches:
    width, height = p.get_width(), p.get_height()
    x, y = p.get_xy()
    ax.annotate('{:.0f}%'.format(height), (p.get_x()+.25*width, p.get_y()+.4*height),
                color = 'white',
               weight = 'bold',
               size = 14)

"""##### 1. Why did you pick the specific chart?

Bar plots are effective for comparing quantitative data across different categories, allowing for easy comparison.

##### 2. What is/are the insight(s) found from the chart?

The churn rates across area codes 408, 415, and 510 are relatively similar, ranging from approximately 14.27% to 14.88%.
There is no significant variation in churn rates observed among the different area codes, suggesting consistent churn behavior across these regions.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Businesses may need to implement targeted retention strategies or investigate common factors contributing to churn across all area codes to improve overall customer retention and reduce churn rates.If churn rates remain consistent despite efforts to mitigate them, it may lead to negative growth as customer retention becomes challenging.

#### Chart - 14 -Comparison of Average Charges by Area Code
"""

# Group the data by 'Area code' and aggregate total charges
group_area = tele_df.groupby("Area code")
total_charges = group_area.agg({"Total intl charge": "mean", "Total day charge": "mean",
                                 "Total eve charge": "mean", "Total night charge": "mean"})
print(total_charges)
# Plot the grouped bar chart
ax = total_charges.plot(kind='bar', figsize=(10, 6), cmap = "coolwarm")

# Beautify the plot
plt.title('Average Charges by Area Code', fontsize=16)
plt.xlabel('Area Code', fontsize=14)
plt.ylabel('Average Charges', fontsize=14)
plt.xticks(rotation=0)
plt.legend(title='Charges', fontsize=10)


plt.show()

"""##### 1. Why did you pick the specific chart?

Bar plots are effective for comparing quantitative data across different categories, allowing for easy comparison of total charges among area codes.

##### 2. What is/are the insight(s) found from the chart?

The insights from the provided data show relatively consistent charges across different area codes for various types of calls. Specifically, while there are slight variations, the charges for international, daytime, evening, and nighttime calls remain relatively stable across area codes 408, 415, and 510

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Such insights can guide businesses in setting competitive pricing strategies and identifying areas for potential revenue growth or cost optimization, ultimately contributing to informed decision-making and enhanced customer satisfaction.

#### Chart - 15 - Average Voicemail Messages for Churned vs. Non-Churned Customers
"""

# Chart - 15 visualization code

# Calculate average number of voicemail messages for churned and non-churned customers
avg_vmail_messages_churned = tele_df[tele_df['Churn'] == True]['Number vmail messages'].mean()
avg_vmail_messages_non_churned = tele_df[tele_df['Churn'] == False]['Number vmail messages'].mean()

# Compare average voicemail messages between churned and non-churned customers
print("Average Voicemail Messages for Churned Customers:", round(avg_vmail_messages_churned,2))
print("Average Voicemail Messages for Non-Churned Customers:", round(avg_vmail_messages_non_churned,2))

# Create a bar plot
plt.figure(figsize=(8,6))
plt.bar(['Churned', 'Non-Churned'], [avg_vmail_messages_churned, avg_vmail_messages_non_churned], width = 0.2, color = ['#1f77b4', '#d62728'])
plt.title('Average Voicemail Messages for Churned vs. Non-Churned Customers')
plt.xlabel('Customer Status')
plt.ylabel('Average Voicemail Messages')
plt.show()

"""##### 1. Why did you pick the specific chart?

Bar plots to illustrate the average voicemail messages for churned and non-churned customers, you can clearly see the differences between the two groups.

##### 2. What is/are the insight(s) found from the chart?

The data reveals a significant disparity in voicemail usage between churned and non-churned customers. Churned customers have an average of 5.12 voicemail messages, notably lower than the 8.6 messages for non-churned customers.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Voicemail messages usage could serve as an indicator of customer engagement and satisfaction. Lower voicemail usage among churned customers presents an opportunity for improving retention strategies by enhancing voicemail features or promoting their benefits. The insight indicating lower voicemail usage among churned customers may also signify a negative growth potential

#### Chart - 16 - Average Account Length by State
"""

# Group the data by state and calculate the mean account length
avg_acc_len = tele_df.groupby("State")["Account length"].mean().sort_values()
print(f'Highest Account length States\n {tele_df.groupby("State")["Account length"].mean().sort_values(ascending = False).head()}')
print(f'Lowest Account length States\n {tele_df.groupby("State")["Account length"].mean().sort_values().head()}')
# Set up the figure and plot
plt.figure(figsize=(20, 6))

# Plot the bar chart
avg_acc_len.plot(kind="bar", cmap = "coolwarm")

# Title and labels
plt.title('Average Account Length by State', fontsize=16)
plt.xlabel('State', fontsize=14)
plt.ylabel('Average Account Length', fontsize=14)

# Show the plot
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Florida (FL): The average account length in Florida is 109.57 months, indicating a relatively long duration of customer accounts.Kentucky (KY): Kentucky has the lowest average account length at 91.83 months, indicating relatively shorter durations of customer accounts compared to other states

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insights on account length across states can help create a positive business impact by informing targeted retention strategies for states with longer average account lengths like Florida and Oklahoma. Conversely, states with shorter average account lengths such as Kentucky and Massachusetts may require focused efforts to improve customer retention and loyalty programs. Identifying states with negative growth potential based on shorter account lengths allows businesses to allocate resources effectively towards enhancing customer satisfaction and loyalty, potentially mitigating churn rates and fostering long-term business sustainability.

#### Chart - 17 -Comparison of Churn Rate, Account Length, and Service Calls between Customers with and without International Plans
"""

# Chart - 17 visualization code
# Filter the dataset based on international plan status
international_yes = tele_df[tele_df['International plan'] == 'Yes']
international_no = tele_df[tele_df['International plan'] == 'No']

# Calculate churn rate for each group
churn_rate_intl_yes = international_yes['Churn'].mean()
churn_rate_intl_no = international_no['Churn'].mean()
print(f"Churn rate with international Plan is : {round(churn_rate_intl_yes,2)}")
print(f"Churn rate without international Plan is : {round(churn_rate_intl_no,2)}")
# Calculate average account length for each group
avg_acct_len_intl_yes = international_yes['Account length'].mean()
avg_acct_len_intl_no = international_no['Account length'].mean()
print(f"Average Account Length of customers having International plan :{round(avg_acct_len_intl_yes,2)}")
print(f"Average Account Length of customers not having International plan :{round(avg_acct_len_intl_no,2)} ")
# Calculate average number of customer service calls for each group
avg_serv_calls_intl_yes = international_yes['Customer service calls'].mean()
avg_serv_calls_intl_no = international_no['Customer service calls'].mean()
print(f"Average service calls made by customers having International plan :{round(avg_serv_calls_intl_yes,2)} ")
print(f"Average service calls made by customers not having International plan :{round(avg_serv_calls_intl_no,2)} ")
# Create a DataFrame for visualization
data = {
    'International plan': ['Yes', 'No'],
    'Churn rate': [churn_rate_intl_yes, churn_rate_intl_no],
    'Avg account length': [avg_acct_len_intl_yes, avg_acct_len_intl_no],
    'Avg service calls': [avg_serv_calls_intl_yes, avg_serv_calls_intl_no]
}
df = pd.DataFrame(data)

# Plotting
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
sns.barplot(x='International plan', y='Churn rate', data=df, width = 0.4, palette=["#408EC6","#DD1717"])
plt.title('Churn Rate by International Plan')

plt.subplot(1, 3, 2)
sns.barplot(x='International plan', y='Avg account length',width = 0.4, data=df, palette=["#408EC6","#DD1717"])
plt.title('Average Account Length by International Plan')

plt.subplot(1, 3, 3)
sns.barplot(x='International plan', y='Avg service calls', width = 0.4, data=df, palette= ["#408EC6","#DD1717"])
plt.title('Average Service Calls by International Plan')

plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

Subplots of bar plots were likely used to visualize the findings because they allow for the simultaneous comparison of multiple categories or groups within the data.

##### 2. What is/are the insight(s) found from the chart?

Churn Rate with International Plan: The churn rate among customers with an international plan is significantly higher at 42%, compared to 11% for customers without an international plan. This indicates that having an international plan may be correlated with a higher likelihood of churn.

Average Account Length: Customers with an international plan have a slightly higher average account length of 104.07 months compared to 100.74 months for those without an international plan. This suggests that customers with international plans tend to stay with the service provider slightly longer on average.

Average Service Calls: Customers with international plans make slightly fewer average service calls (1.46) compared to those without international plans (1.57). This could indicate that customers with international plans may be more self-sufficient or encounter fewer service-related issues.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insights gained can indeed lead to a positive business impact by highlighting potential areas for improvement and optimization. However, the significantly higher churn rate among customers with international plans indicates a concerning trend that may lead to negative growth.

#### Chart - 18 - Comparison of Churn Rate, Account Length, and Service Calls between Customers with and without Voice mail Plans
"""

# Chart - 17 visualization code
# Filter the dataset based on international plan status
vmp_yes = tele_df[tele_df['Voice mail plan'] == 'Yes']
vmp_no = tele_df[tele_df['Voice mail plan'] == 'No']

# Calculate churn rate for each group
churn_rate_vmp_yes = vmp_yes['Churn'].mean()
churn_rate_vmp_no = vmp_no['Churn'].mean()
print(f"Churn rate with Voice mail plan is : {round(churn_rate_vmp_yes,2)}")
print(f"Churn rate without Voice mail plan is : {round(churn_rate_vmp_no,2)}")
# Calculate average account length for each group
avg_acct_len_vmp_yes = vmp_yes['Account length'].mean()
avg_acct_len_vmp_no = vmp_no['Account length'].mean()
print(f"Average Account Length of customers having Voice mail plan : {round(avg_acct_len_vmp_yes,2)}")
print(f"Average Account Length of customers not having Voice mail plan : {round(avg_acct_len_vmp_no,2)} ")
# Calculate average number of customer service calls for each group
avg_serv_calls_vmp_yes = vmp_yes['Customer service calls'].mean()
avg_serv_calls_vmp_no = vmp_no['Customer service calls'].mean()
print(f"Average service calls made by customers having Voice mail plan  : {round(avg_serv_calls_vmp_yes,2)} ")
print(f"Average service calls made by customers not having Voice mail plan : {round(avg_serv_calls_vmp_no,2)} ")
# Create a DataFrame for visualization
data_vmp= {
    'Voice mail plan': ['Yes', 'No'],
    'Churn rate': [churn_rate_vmp_yes, churn_rate_vmp_no],
    'Avg account length': [avg_acct_len_vmp_yes, avg_acct_len_vmp_no],
    'Avg service calls': [avg_serv_calls_vmp_yes, avg_serv_calls_vmp_no]
}
df_vmp= pd.DataFrame(data_vmp)

# Plotting
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
sns.barplot(x='Voice mail plan', y='Churn rate', data=df_vmp, width = 0.4, palette =["#408EC6","#DD1717"])
plt.title('Churn Rate by Voice mail plan')

plt.subplot(1, 3, 2)
sns.barplot(x='Voice mail plan', y='Avg account length', data=df_vmp, width = 0.4, palette =["#408EC6","#DD1717"])
plt.title('Average Account Length by Voice mail plan')

plt.subplot(1, 3, 3)
sns.barplot(x='Voice mail plan', y='Avg service calls', data=df_vmp,width = 0.4, palette =["#408EC6","#DD1717"])
plt.title('Average Service Calls by Voice mail plan')

plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

Subplots of bar plots were likely used to visualize the findings because they allow for the simultaneous comparison of multiple categories or groups within the data.

##### 2. What is/are the insight(s) found from the chart?

Churn Rate: Customers with a voice mail plan have a lower churn rate of 9% compared to 17% for those without a voice mail plan. This suggests that having a voice mail plan may contribute to higher customer retention.

Average Account Length: The average account length is slightly higher for customers with a voice mail plan (101.25 months) compared to those without (100.99 months). This indicates that customers with voice mail plans tend to stay with the service provider slightly longer on average.

Average Service Calls: Customers with voice mail plans make slightly fewer average service calls (1.52) compared to those without (1.58). This could suggest that customers with voice mail plans may encounter fewer service-related issues or have different communication preferences.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The gained insights are likely to contribute positively to business impact by highlighting the potential benefits of offering voice mail plans, such as lower churn rates and slightly longer customer tenure. However, the marginally higher average service calls made by customers without voice mail plans could indicate a need for further investigation into service quality or customer satisfaction in this segment.

#### Chart - 19 - Average Charges per Minute for Different Time Periods
"""

# Aggregate the charges per minute
charges_per_min = tele_df.agg({"day_charges_per_min": "mean",
                               "eve_charges_per_min": "mean",
                               "night_charges_per_min": "mean",
                               "int_charges_per_min": "mean"})
print(f"Average charges per minutes for different usage patterns are\n{charges_per_min}")
# Plot the aggregated charges per minute
charges_per_min.plot(kind="bar", color = ["#FB5E4F","#FD71A0","#F9B234","#209CC2"])

# Add title and labels
plt.title('Average Charges per Minute for Different Time Periods')
plt.xlabel('Time Period')
plt.ylabel('Average Charges')

# Show the plot
plt.show()

"""##### 1. Why did you pick the specific chart?

It effectively displays comparisons between multiple categories, making it suitable for showcasing the distribution of charges across various segments

##### 2. What is/are the insight(s) found from the chart?

The insights from the average charges per minute for different usage patterns reveal varying pricing structures and potential revenue drivers. Customers incur the highest charges per minute for international calls, suggesting that international calling services contribute significantly to overall revenue. Conversely, nighttime calls incur the lowest charges per minute, indicating a possible area for incentivizing increased usage or exploring cost-effective service enhancements.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Identifying high charges per minute for international calls suggests potential opportunities to attract more customers to international plans, thereby increasing revenue. However, the lower charges per minute for nighttime calls may indicate a need for strategies to boost usage during these periods to maximize revenue.

#### Chart - 20 - Average Revenue Across Different Area Codes
"""

# Group the data by 'Area code' and calculate total revenue for each time period
group_area = tele_df.groupby("Area code")
revenue = group_area.agg({"Revenue_day": "mean", "Revenue_eve": "mean", "Revenue_night": "mean"})
print(revenue)
# Plot the bar chart
revenue.plot(kind="bar", color=['#1f77b4', '#d62728', '#2b4871'])

# Add labels and title
plt.xlabel('Area Code')
plt.ylabel('Average Revenue')
plt.title('Average Revenue Across Different Area Codes')

# Show the plot
plt.show()

"""##### 1. Why did you pick the specific chart?

A bar plot is chosen for visualizing revenue data across different area codes because it effectively displays and compares the revenue figures for each category

##### 2. What is/are the insight(s) found from the chart?

Area code 415 generates the highest revenue across all three time periods, indicating potentially higher customer activity or premium services in that region.
Despite slight variations, revenue from daytime, evening, and nighttime usage remains relatively consistent across area codes 408 and 510.
Revenue from evening calls is notably consistent across all three area codes, suggesting similar usage patterns during this time period.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insights on revenue distribution across area codes can guide targeted marketing efforts and service enhancements, fostering positive business impact. However, disparities in revenue among area codes may lead to neglect of regions with lower potential, hindering growth. Analyzing usage patterns during different time periods can optimize pricing strategies and promotions, further boosting revenue. Ignoring these insights may result in missed opportunities and negative growth potential for the telecom company

#### Chart - 21 - Average International Revenue per Area Code
"""

# Chart - 20 visualization code

# Grouping the data and aggregating total international revenue
group_area = tele_df.groupby("Area code")
intl_revenue = group_area.agg({"Revenue_intl":"mean"})
print(intl_revenue)
# Plotting the bar plot with custom colors
ax = intl_revenue.plot(kind="bar", cmap= "coolwarm", figsize=(7, 6), width = 0.6)

# Adding labels and title
ax.set_xlabel("Area Code")
ax.set_ylabel("Average International Revenue")
ax.set_title("Average International Revenue per Area Code")

# Rotating x-axis labels for better readability
plt.xticks(rotation=45)

# Displaying the plot
plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

A bar plot because it effectively compares the international revenue across different area codes.

##### 2. What is/are the insight(s) found from the chart?

The data shows that the average revenue from international calls is relatively consistent across area codes 408, 415, and 510, with values around $30. This suggests that there's no significant variation in international call revenue contribution among these areas.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insights on consistent average revenue from international calls across area codes suggest a stable revenue stream, which can positively impact business planning and financial projections.

#### Chart - 22 - Churn Percentage by Number of Customer Service Calls
"""

# Group by 'Customer service calls' and calculate churn percentage
cust_service_churn = (tele_df.groupby("Customer service calls")["Churn"].mean() * 100).reset_index(name="Churn%")

# Plot the churn percentage
plt.figure(figsize=(8, 6))
plt.bar(cust_service_churn["Customer service calls"], cust_service_churn["Churn%"], color='#6495ED')

# Add labels and title
plt.xlabel('Number of Customer Service Calls')
plt.ylabel('Churn Percentage')
plt.title('Churn Percentage by Number of Customer Service Calls')

# Show the plot
plt.grid(True)
plt.show()

"""##### 1. Why did you pick the specific chart?

This visualization method allows for easy comparison and identification of trends, helping to pinpoint potential areas for improvement in customer service strategies.

##### 2. What is/are the insight(s) found from the chart?

Customers with fewer customer service calls tend to have lower churn rates, with percentages ranging from around 10% to 13% for 0 to 3 calls.
Churn rates increase significantly when customers make more calls, especially beyond 3 calls, reaching exceptionally high percentages of 45% and above for 4 to 9 calls.

There is a drastic increase in churn rate for customers with 4 or more calls, indicating potential dissatisfaction or issues that lead them to contact customer service repeatedly.
The highest churn rate of 100% is observed for customers who made 9 customer service calls, suggesting severe dissatisfaction or unresolved issues that result in churn.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insights gained from analyzing customer churn in relation to the number of customer service calls can significantly benefit the business by highlighting areas for improvement in customer service satisfaction. However, the observed increase in churn rates with higher call volumes indicates negative growth, suggesting potential issues or dissatisfaction among customers requiring attention to enhance service quality and retention strategies.

#### Chart - 23 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
plt.figure(figsize=(16, 10))
sns.heatmap(tele_df.corr(numeric_only = True), annot=True, linewidths=0.5, cmap='coolwarm', fmt=".2f", cbar=True)
plt.title("Correlation of the columns", fontsize=15)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.show()

"""##### 1. Why did you pick the specific chart?

tThe heatmap represents the correlation coefficient between two variables, ranging from -1 to 1. Positive values indicate a positive correlation, negative values indicate a negative correlation, and values close to 0 indicate no correlation

##### 2. What is/are the insight(s) found from the chart?

Positive correlation between variables such as total day minutes, total day charge, customer service calls, and revenue from day calls. On the other hand, there's a negative correlation with the number of voice mail messages and international calls. Customer service call is positively correlated only with area code

#### Chart - 24 - Pair Plot
"""

# Pair Plot visualization code

sns.pairplot(tele_df, hue='Churn', diag_kind='kde')
plt.show()

"""##### 1. Why did you pick the specific chart?

A pair plot is chosen to visualize the relationships between pairs of numerical variables in the dataset

##### 2. What is/are the insight(s) found from the chart?

The pair plot analysis reveals that there is a less linear relationship between variables, with data points exhibiting clustering and overlap, particularly among churned customers. Non-churn data appear more symmetrical compared to churned data, which exhibit non-symmetrical distributions. These insights suggest that churned customers may exhibit more diverse behavior patterns compared to non-churn customers, potentially indicating underlying factors contributing to churn.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

1. Retention Strategies: Implement effective retention strategies to address the churn rate of approximately 14.49%. This could involve enhancing customer satisfaction through personalized offers, loyalty programs, and improved customer service.

2. International Plan Promotion: Encourage more customers to subscribe to the International plan to reduce churn rates among this group and potentially increase revenue from international calls. Customers with both an International plan and a Voice mail plan exhibit the lowest churn rate among the analyzed groups. This indicates that offering bundled services or incentives can effectively reduce churn and improve customer loyalty.

3. Voice Mail Plan Adoption: Promote the Voice mail plan to increase adoption among customers, as those with a Voice mail plan exhibit lower churn rates compared to those without.

4. Regional Analysis: Investigate and address high churn rates in states like New Jersey, California, and Texas by identifying and resolving regional-specific challenges or customer dissatisfaction factors.

5. Revenue Optimization by Area Code: Focus on revenue generation strategies in area codes with lower revenue figures, such as Area Code 510(Oakland), to improve overall revenue performance.

6. Account Length Analysis: Implement targeted retention efforts for customers with longer account lengths.

7. Customer Service Call Management: Improve service quality and issue resolution processes to reduce customer dissatisfaction and subsequent churn.

8. Product Offering Optimization: Continuously assess and optimize product offerings, such as daytime, evening, and international call plans, based on revenue contribution and customer preferences to maximize revenue and customer satisfaction.

# **Conclusion**

Effective retention strategies are crucial, given the 14.49% churn rate, emphasizing the need to address factors leading to customer attrition.

Offering International and Voice mail plans can mitigate churn, as evidenced by lower churn rates among subscribers compared to non-subscribers.

Regional trends reveal areas for improvement, with states like New Jersey, California, and Texas exhibiting higher churn rates, necessitating targeted retention efforts.

Revenue optimization opportunities exist, particularly in area codes with lower revenue figures, suggesting a focus on revenue generation strategies.

Analyzing account length and customer service call patterns can inform tailored retention efforts, aiming to reduce churn and enhance overall customer satisfaction.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""